- name: Install MySQL
  apt: pkg={{ item }} state=latest
  with_items:
    - mariadb-server
    - mariadb-client
    - mysqltuner

# Configure MySQL
- name: ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true

- name: update mysql root password for all root accounts
  mysql_user: name=root host=localhost password={{ mysql_root_db_password }}

- name: Copy .my.cnf file with root password credentials
  template: src=root.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_db_password }}
  with_items:
    - 127.0.0.1
    - ::1

- name: Create database
  mysql_db: db={{ mysql_db_name }} state=present

- name: Create mysql user account
  mysql_user: name={{ mysql_user_name }} host=localhost password={{ mysql_user_name_password }} priv='{{ mysql_user_name }}.*:ALL'

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost

- name: Remove the test database
  mysql_db: name=test state=absent
  notify: restart mysql